name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Lint and format (check only)
        run: |
          black --check .
          isort --check-only .
          ruff .
          nbqa black --check notebooks || true
          nbqa ruff notebooks || true

      - name: Execute notebook
        run: |
          jupyter nbconvert --to notebook --execute --inplace notebooks/HW_7.ipynb --ExecutePreprocessor.timeout=600
